pipeline {
    agent any

    environment {
        LC_ALL = 'en_US.UTF-8'
        LANG = 'en_US.UTF-8'
    }

    stages {
        stage('Setup') {
            steps {
                sh 'bundle install --path vendor/bundle'
            }
        }

        stage('Test') {
            steps {
                sh 'bundle exec fastlane test'
            }
        }

        stage('Build') {
            steps {
                sh 'bundle exec fastlane build'
            }
        }

        stage('Firebase') {
            when {
                branch 'develop'
            }
            steps {
                sh 'bundle exec fastlane firebase'
            }
        }

        stage('TestFlight') {
            when {
                branch 'main'
            }
            steps {
                sh 'bundle exec fastlane beta'
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success {
            echo 'Build succeeded!'
        }
        failure {
            echo 'Build failed!'
        }
    }
}
